name: CI

#Controls when the workflow will run
on:
push:
 branches: ["main"]
pull_request:
 branches: ["main"]

workflow_dispatch:


job:
 build:
  runs-on: ubuntu-latest
  steps:
   - users: actions/checkout@v3
   
   - name: Run a one-line script
     run: echo Hello, world!

   - name: Run a multi-line script
     run: |
       echo Add other actions to build,
       echo test, and deploy your project.
